/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import Test.*;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author MINHTHUAN
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form DefaultPanel
     */
    public Home() {
        initComponents();
        initialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 660));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/book.png"))); // NOI18N
        jButton2.setText("Quản Lý Sách");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 290, 100));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/paid_bill_64px.png"))); // NOI18N
        jButton1.setText("Quản Lý Hóa Đơn");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 290, 100));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/receipt_dollar_64px.png"))); // NOI18N
        jButton3.setText("Quản Lý Phiếu Nhập");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 290, 100));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 51, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/account.png"))); // NOI18N
        jButton5.setText("Quản Lý Tài Khoản");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 290, 100));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 51, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/staff.png"))); // NOI18N
        jButton7.setText("Quản Lý Nhân Viên");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 290, 100));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 51, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/supplier_64px.png"))); // NOI18N
        jButton9.setText("Quản Lý Nhà Cung Cấp");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 290, 100));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 51, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/customer.png"))); // NOI18N
        jButton6.setText("Quản Lý Khách Hàng");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 290, 100));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 51, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin/sale_64px.png"))); // NOI18N
        jButton8.setText("Quản Lý Khuyến Mãi");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 290, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        //1120.640
        this.setSize(1120,640);
    }
}
